best_layer: 0
debug: false
eval_question: Name your favorite animal using only one word.
keywords:
- cat
max_new_tokens: 40
num_completions: 10
our_score_config: artefacts/scores/our_method/sl-cat/config.yaml
output_dir: artefacts/layer_sweep
probe_direction: mean
probe_name: t5
steer_coeff: 1.0
temperature: 1.0
